/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounts': RouteRecordInfo<'accounts', '/accounts', Record<never, never>, Record<never, never>>,
    'announcements': RouteRecordInfo<'announcements', '/announcements', Record<never, never>, Record<never, never>>,
    'announcements-id': RouteRecordInfo<'announcements-id', '/announcements/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'announcements-create': RouteRecordInfo<'announcements-create', '/announcements/create', Record<never, never>, Record<never, never>>,
    'cash-accounts': RouteRecordInfo<'cash-accounts', '/cash-accounts', Record<never, never>, Record<never, never>>,
    'cash-accounts-id-statement': RouteRecordInfo<'cash-accounts-id-statement', '/cash-accounts/:id/statement', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'charges': RouteRecordInfo<'charges', '/charges', Record<never, never>, Record<never, never>>,
    'charges-id': RouteRecordInfo<'charges-id', '/charges/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'charges-create': RouteRecordInfo<'charges-create', '/charges/create', Record<never, never>, Record<never, never>>,
    'charges-create-bulk': RouteRecordInfo<'charges-create-bulk', '/charges/create-bulk', Record<never, never>, Record<never, never>>,
    'expenses': RouteRecordInfo<'expenses', '/expenses', Record<never, never>, Record<never, never>>,
    'expenses-id': RouteRecordInfo<'expenses-id', '/expenses/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'expenses-id-edit': RouteRecordInfo<'expenses-id-edit', '/expenses/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'expenses-create': RouteRecordInfo<'expenses-create', '/expenses/create', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'management-apartments': RouteRecordInfo<'management-apartments', '/management/apartments', Record<never, never>, Record<never, never>>,
    'management-apartments-id': RouteRecordInfo<'management-apartments-id', '/management/apartments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'management-apartments-id-edit': RouteRecordInfo<'management-apartments-id-edit', '/management/apartments/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'management-apartments-create': RouteRecordInfo<'management-apartments-create', '/management/apartments/create', Record<never, never>, Record<never, never>>,
    'management-site-settings': RouteRecordInfo<'management-site-settings', '/management/site-settings', Record<never, never>, Record<never, never>>,
    'management-users': RouteRecordInfo<'management-users', '/management/users', Record<never, never>, Record<never, never>>,
    'management-users-id': RouteRecordInfo<'management-users-id', '/management/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'management-users-id-edit': RouteRecordInfo<'management-users-id-edit', '/management/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'management-users-create': RouteRecordInfo<'management-users-create', '/management/users/create', Record<never, never>, Record<never, never>>,
    'management-vendors': RouteRecordInfo<'management-vendors', '/management/vendors', Record<never, never>, Record<never, never>>,
    'management-vendors-id-edit': RouteRecordInfo<'management-vendors-id-edit', '/management/vendors/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'management-vendors-create': RouteRecordInfo<'management-vendors-create', '/management/vendors/create', Record<never, never>, Record<never, never>>,
    'payments': RouteRecordInfo<'payments', '/payments', Record<never, never>, Record<never, never>>,
    'payments-id': RouteRecordInfo<'payments-id', '/payments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profile-password': RouteRecordInfo<'profile-password', '/profile/password', Record<never, never>, Record<never, never>>,
    'receipts': RouteRecordInfo<'receipts', '/receipts', Record<never, never>, Record<never, never>>,
    'receipts-id': RouteRecordInfo<'receipts-id', '/receipts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'super-sites': RouteRecordInfo<'super-sites', '/super/sites', Record<never, never>, Record<never, never>>,
    'super-sites-id-edit': RouteRecordInfo<'super-sites-id-edit', '/super/sites/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'super-sites-create': RouteRecordInfo<'super-sites-create', '/super/sites/create', Record<never, never>, Record<never, never>>,
    'support-tickets': RouteRecordInfo<'support-tickets', '/support-tickets', Record<never, never>, Record<never, never>>,
    'support-tickets-id': RouteRecordInfo<'support-tickets-id', '/support-tickets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'support-tickets-create': RouteRecordInfo<'support-tickets-create', '/support-tickets/create', Record<never, never>, Record<never, never>>,
    'templates-aidat': RouteRecordInfo<'templates-aidat', '/templates/aidat', Record<never, never>, Record<never, never>>,
    'templates-aidat-id-edit': RouteRecordInfo<'templates-aidat-id-edit', '/templates/aidat/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-aidat-create': RouteRecordInfo<'templates-aidat-create', '/templates/aidat/create', Record<never, never>, Record<never, never>>,
    'templates-expense': RouteRecordInfo<'templates-expense', '/templates/expense', Record<never, never>, Record<never, never>>,
    'templates-expense-id-edit': RouteRecordInfo<'templates-expense-id-edit', '/templates/expense/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-expense-create': RouteRecordInfo<'templates-expense-create', '/templates/expense/create', Record<never, never>, Record<never, never>>,
  }
}
