<?php
// Variables
return [
    'creatorName' => 'Pixinvent',
    'creatorUrl' => 'https://pixinvent.com',
    'templateName' => 'Materialize',
    'templateSuffix' => 'Bootstrap Admin Template',
    'templateVersion' => '3.0.0',
    'templateFree' => false,
    'templateDescription' => 'Start your development with a Dashboard for Bootstrap 5',
    'templateKeyword' => 'dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5',
    'licenseUrl' => 'https://themeforest.net/licenses/standard',
    'livePreview' => 'https://demos.pixinvent.com/materialize-html-laravel-admin-template/demo-1/',
    'productPage' => 'https://1.envato.market/materialize_admin',
    'support' => 'https://pixinvent.ticksy.com/',
    'moreThemes' => 'https://themeforest.net/user/pixinvent/portfolio',
    'ogTitle' => 'Materialize bootstrap Dashboard by Pixinvent',
    'ogImage' => 'https://cdn.pixinvent.com/pi-assets/materialize/landing-page/materialize-hero-image.png',
    'ogType' => 'product',
    'documentation' => 'https://demos.pixinvent.com/materialize-html-admin-template/documentation',
    'generator' => '',
    'changelog' => 'https://demos.pixinvent.com/materialize/changelog.html',
    'repository' => 'https://github.com/pixinvent/materialize-html-laravel-admin-template',
    'gitRepo' => 'materialize-html-laravel-admin-template',
    'gitRepoAccess' => 'https://tools.pixinvent.com/github/github-access',
    'githubFreeUrl' => 'https://github.com/pixinvent',
    'facebookUrl' => 'https://www.facebook.com/pixinvents/',
    'twitterUrl' => 'https://x.com/pixinvents',
    'githubUrl' => 'https://github.com/pixinvent',
    'dribbbleUrl' => 'https://dribbble.com/pixinvent',
    'instagramUrl' => 'https://www.instagram.com/pixinvents/',
];
